version: '3'
services:
  # Accessible Course Material
  accessible-course-material:
    build:
      context: ../accessible-course-material
      dockerfile: docker/Dockerfile
    ports:
      - '4003:8000'
  
  # Visualizing Concepts
  visualizing-concepts:
    build:
      context: ../visualizing-concepts
      dockerfile: docker/Dockerfile
    ports:
      - '4004:8000'

  # Course Exercises
  course-exercises-web-server:
    build:
      context: ../course-exercises/web_server
    ports:
      - '4000:4000'

  course-exercises-data-server:
    build:
      context: ../course-exercises/data_server
    ports:
      - '4001:4001'

  course-exercises-database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - data-volume:/data/db
    ports:
      - '4002:27017'

  # Nginx
  nginx-ssl-proxy:
    build:
      context: nginx-ssl/
    restart: always
    environment:
      SERVERNAME: discretemath.ca
      EXTRANAMES: discretemath.ca
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt"

# Volume for MongoDB
volumes:
  data-volume: